### ISSUE TITLE
Embedded config sections

### ISSUE THREAD

**Issue by dgrijalva** [ngmoco/timber#1]
I'd rather not have to have a separate config file for my logs from the rest of my service.  If we cleaned up and published the config structures (and a couple methods), it would make it trivial to embed timber config in a different config file...

**Comment by smw1218** [comment]
I think this should be possible right now. Is there a specific issue you're having?

**Comment by smw1218** [comment]
the xml configs were just broken for go1 anyway due to changes in the xml parser.  this is fixed now.

**Comment by smw1218** [comment]
is this working for you now with the latest updates?

**Comment by dgrijalva** [comment]
I haven't really gone back. I'll be looking at this next week

-dave

**Comment by smw1218** [comment]
No longer an issue
